# 配置文件参考 Helm 仓库说明
# https://openebs.github.io/jiva-operator/
cleanup:
  image:
    registry: "registry.dockermirror.com/"
helper:
  image: "registry.dockermirror.com/openebs/linux-utils"
jiva:
  enabled: true
  replicas: 1
  image: "registry.dockermirror.com/openebs/jiva"
  defaultStoragePath: "/var/openebs"
  csiController:
    driverRegistrar:
      image:
        registry: k8s.mirror.nju.edu.cn/
        repository: sig-storage/csi-node-driver-registrar
        tag: v2.10.0
    resizer:
      image:
        registry: k8s.mirror.nju.edu.cn/
        repository: sig-storage/csi-resizer
        tag: v1.8.0
    attacher:
      image:
        registry: k8s.mirror.nju.edu.cn/
        repository: sig-storage/csi-attacher
        tag: v4.3.0
    provisioner:
      image:
        registry: k8s.mirror.nju.edu.cn/
        repository: sig-storage/csi-provisioner
        tag: v3.6.3

    livenessprobe:
      image:
        registry: k8s.mirror.nju.edu.cn/
        repository: sig-storage/livenessprobe
        tag: v2.10.0

  csiNode:
    livenessprobe:
      image:
        registry: k8s.mirror.nju.edu.cn/
        repository: sig-storage/livenessprobe
        tag: v2.10.0
    driverRegistrar:
      image:
        registry: k8s.mirror.nju.edu.cn/
        repository: sig-storage/csi-node-driver-registrar
        tag: v2.10.0

  jivaOperator:
    controller:
      image:
        registry: "registry.dockermirror.com/"
        repository: openebs/jiva
    exporter:
      image:
        repository: "registry.dockermirror.com/openebs/m-exporter"
        tag: 3.6.0
    replica:
      image:
        registry: "registry.dockermirror.com/"
        repository: openebs/jiva
    image:
      registry: "registry.dockermirror.com/"
      repository: openebs/jiva-operator

  localpv-provisioner:
    localpv:
      image:
        registry: "registry.dockermirror.com/"
    helperPod:
      image:
        registry: "registry.dockermirror.com/"
    openebs-ndm:
      helperPod:
        image:
          registry: "registry.dockermirror.com/"
      ndm:
        image:
          registry: "registry.dockermirror.com/"
      ndmExporter:
        image:
          registry: "registry.dockermirror.com/"
      ndmOperator:
        image:
          registry: "registry.dockermirror.com/"
  jivaCSIPlugin:
    image:
      registry: "registry.dockermirror.com/"
      repository: openebs/jiva-csi

localprovisioner:
  image: registry.dockermirror.com/openebs/provisioner-localpv

ndm:
  image: registry.dockermirror.com/openebs/node-disk-manager

ndmOperator:
  image: registry.dockermirror.com/openebs/node-disk-operator

policies:
  monitoring:
    image: registry.dockermirror.com/openebs/m-exporter

provisioner:
  image: registry.dockermirror.com/openebs/openebs-k8s-provisioner

snapshotOperator:
  controller:
    image: registry.dockermirror.com/openebs/snapshot-controller
  provisioner:
    image: registry.dockermirror.com/openebs/snapshot-provisioner

webhook:
  image: registry.dockermirror.com/openebs/admission-server
